spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false #强行转换成json数据
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,\
      classpath:/static/,classpath:/public/,file:E:/develop/fileUpload/


server:
  port: 8083

#分页插件
pagehelper:
  helper-dialect: mysql

mybatis:
  type-handlers-package: com.cskaoyan.mall.typehandler

#控制台信息
logging:
  level:
    com.cskaoyan.mall.mapper: debug
    com.cskaoyan.mall.service: error


aliyun:
  accessKeyId: LTAI4Fr5gfYhcVjLMqeRGbuT
  accessKeySecret: IrkcHu6dZyrjPZRushgO76P5392HJ1
  oss:
    bucket: cskaoyan
    endPoint: oss-cn-beijing.aliyuncs.com
  sms:
    signName: stone4j
    templateCode: SMS_173765187